export const CountyCodeMapCA: any[] = [
    { code: '6099', name: 'Stanislaus County' },
    { code: '6031', name: 'Kings County' },
    { code: '6091', name: 'Sierra County' },
    { code: '6093', name: 'Siskiyou County' },
    { code: '6095', name: 'Solano County' },
    { code: '6037', name: 'Los Angeles County' },
    { code: '6097', name: 'Sonoma County' },
    { code: '6011', name: 'Colusa County' },
    { code: '6013', name: 'Contra Costa County' },
    { code: '6015', name: 'Del Norte County' },
    { code: '6017', name: 'El Dorado County' },
    { code: '6115', name: 'Yuba County' },
    { code: '6019', name: 'Fresno County' },
    { code: '6035', name: 'Lassen County' },
    { code: '6111', name: 'Ventura County' },
    { code: '6047', name: 'Merced County' },
    { code: '6113', name: 'Yolo County' },
    { code: '6077', name: 'San Joaquin County' },
    { code: '6039', name: 'Madera County' },
    { code: '6073', name: 'San Diego County' },
    { code: '6071', name: 'San Bernardino County' },
    { code: '6033', name: 'Lake County' },
    { code: '6057', name: 'Nevada County' },
    { code: '6051', name: 'Mono County' },
    { code: '6053', name: 'Monterey County' },
    { code: '6025', name: 'Imperial County' },
    { code: '6043', name: 'Mariposa County' },
    { code: '6089', name: 'Shasta County' },
    { code: '6087', name: 'Santa Cruz County' },
    { code: '6029', name: 'Kern County' },
    { code: '6085', name: 'Santa Clara County' },
    { code: '6083', name: 'Santa Barbara County' },
    { code: '6067', name: 'Sacramento County' },
    { code: '6081', name: 'San Mateo County' },
    { code: '6007', name: 'Butte County' },
    { code: '6005', name: 'Amador County' },
    { code: '6075', name: 'San Francisco County' },
    { code: '6003', name: 'Alpine County' },
    { code: '6079', name: 'San Luis Obispo County' },
    { code: '6001', name: 'Alameda County' },
    { code: '6109', name: 'Tuolumne County' },
    { code: '6107', name: 'Tulare County' },
    { code: '6105', name: 'Trinity County' },
    { code: '6103', name: 'Tehama County' },
    { code: '6009', name: 'Calaveras County' },
    { code: '6101', name: 'Sutter County' },
    { code: '6065', name: 'Riverside County' },
    { code: '6041', name: 'Marin County' },
    { code: '6061', name: 'Placer County' },
    { code: '6045', name: 'Mendocino County' },
    { code: '6063', name: 'Plumas County' },
    { code: '6021', name: 'Glenn County' },
    { code: '6059', name: 'Orange County' },
    { code: '6049', name: 'Modoc County' },
    { code: '6069', name: 'San Benito County' },
    { code: '6027', name: 'Inyo County' },
    { code: '6055', name: 'Napa County' },
    { code: '6023', name: 'Humboldt County' }
];
